---
# Handlers for install role
- name: restart otelcol-contrib
  systemd:
    name: otelcol-contrib
    state: restarted
    daemon_reload: yes
  when: ansible_os_family in ['RedHat', 'Debian']

- name: restart otelcol-contrib windows
  win_service:
    name: otelcol-contrib
    state: restarted
  when: ansible_os_family == 'Windows'