---
# Tasks for upgrading OpenTelemetry Collector
- name: Check installation status
  include_tasks: "{{ (ansible_os_family | lower ~ '_check.yml') if ansible_os_family == 'Windows' else 'linux_check.yml' }}"
  when: ansible_os_family in ['RedHat', 'Debian', 'Windows']

- name: Fail if OpenTelemetry Collector is not installed
  fail:
    msg: "OpenTelemetry Collector is not installed on {{ inventory_hostname }}. Please run the install_playbook first."
  when: not otelcol_installed | default(false)

- name: Upgrade OpenTelemetry Collector
  include_tasks: "{{ (ansible_os_family | lower ~ '_upgrade.yml') if ansible_os_family == 'Windows' else 'linux_upgrade.yml' }}"
  when: ansible_os_family in ['RedHat', 'Debian', 'Windows']