---
# Handlers for deployment role
- name: restart otelcol-contrib
  service:
    name: otelcol-contrib
    state: restarted
  become: true
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Restart Otelcol-contrib Windows
  ansible.windows.win_service:
    name: otelcol-contrib
    state: restarted
  when: ansible_os_family == 'Windows'
  