---
# Handlers for upgrade role
- name: restart otelcol-contrib
  service:
    name: otelcol-contrib
    state: restarted
  when: ansible_os_family in ['RedHat', 'Debian']

- name: restart otelcol-contrib Windows
  win_service:
    name: otelcol-contrib
    state: restarted
  when: ansible_os_family == 'Windows'