---
# Common tasks for all hosts
- name: Set OS-specific variables
  include_tasks: set_variables.yml
  tags: always

# Use includes to handle OS-specific tasks with a simpler approach
- name: Create required directories for Linux
  include_tasks: linux_directories.yml
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Create required directories for Windows
  include_tasks: windows_directories.yml
  when: ansible_os_family == 'Windows'
  