---
# Common tasks for all hosts
- name: Set OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../inventory/group_vars/{{ ansible_os_family | lower }}/all.yml"
    - "../inventory/group_vars/linux/all.yml"  # Fallback for RedHat/Debian
    - "../inventory/group_vars/all/all.yml"
  tags: always

- name: Create otelcol-contrib directories
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ otelcol_config_dir }}"
    - "{{ otelcol_log_dir }}"
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Create otelcol-contrib directories (Windows)
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ otelcol_config_dir }}"
    - "{{ otelcol_log_dir }}"
  when: ansible_os_family == 'Windows'