# inventory/hosts.yml
all:
  children:
    linux:
      hosts:
        Redhat-Omni-1:
          ansible_host: Redhat-Omni-1
          ansible_user: ansible
          ansible_password: "{{ linux_ansible_password }}"
          ansible_become_password: "{{ linux_ansible_password }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_connection: ssh
    windows:
      hosts:
        Windows-Omni-1:
          ansible_host: Windows-Omni-1
          ansible_user: "ansible"
    sandbox:
      hosts:
        Redhat-Omni-1:
        Windows-Omni-1:
    app_a:
      hosts:
    sql_servers:
      hosts:
    production:
      hosts:
