# inventory/hosts.yml
all:
  children:
    linux_hosts:
      hosts:
        redhat:
          ansible_user: ansible
          ansible_ssh_private_key_file: /home/jamel/.ssh/id_ed25519
    windows_hosts:
      hosts:
        windows:
          ansible_user: ansible
          ansible_password: "{{ windows_ansible_password }}"
          ansible_connection: psrp
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_transport: ntlm
          ansible_port: 5986  # HTTPS port for WinRM
    sandbox:
      hosts:
        windows:
        redhat:
    app_a:
      hosts:
    sql_servers:
      hosts:
    production:
      hosts: