# inventory/hosts.yml
all:
  children:
    linux:
      hosts:
        redhat1:
          ansible_host: Redhat-Omni-1
          ansible_user: ansible
          ansible_password: "{{ linux_ansible_password }}"
          ansible_become_password: "{{ linux_ansible_password }}"  # Add this line for sudo
    windows:
      hosts:
        windows1:
          ansible_host: Windows-Omni-1
          ansible_user: ansible
          ansible_password: "{{ windows_ansible_password }}"
          ansible_winrm_server_cert_validation: ignore
    sandbox:
      hosts:
        windows:
        redhat:
    app_a:
      hosts:
    sql_servers:
      hosts:
    production:
      hosts:
