ansible_connection: psrp
ansible_psrp_transport: ntlm
ansible_psrp_protocol: https
ansible_psrp_port: 5986
ansible_psrp_ignore_proxy: true
ansible_psrp_verify: false
ansible_psrp_cert_validation: ignore
ansible_password: "{{ windows_ansible_password }}"
