---
# Check if OpenTelemetry Collector is installed on Linux
- name: Check if otelcol-contrib is installed (Linux)
  stat:
    path: "{{ otelcol_binary_path }}"
  register: otelcol_binary

- name: Set fact for installation status
  set_fact:
    otelcol_installed: "{{ otelcol_binary.stat.exists }}"
