---
- name: Install OpenTelemetry Collector
  hosts: all
  gather_facts: true
  
  vars:
    otelcol_force_install: false  # Default to not forcing installation
  
  pre_tasks:
    - name: Create temp directory (Windows)
      win_file:
        path: C:\Temp
        state: directory
      when: ansible_os_family == 'Windows'
      tags:
        - prerequisites
  
  roles:
    - role: common
      tags: [common, install]
    
    - role: install
      tags: [install]
    
    - role: validation
      tags: [validate]