---
- name: Install OpenTelemetry Collector
  hosts: all
  gather_facts: true
  
  vars:
    otelcol_force_install: false  # Default to not forcing installation
  
  pre_tasks:
    - name: Include OS-specific variables
      include_vars: "{{ item }}"
      with_first_found:
      - "../inventory/group_vars/{{ 'linux' if ansible_os_family in ['RedHat', 'Debian'] else ansible_os_family | lower }}/all.yml"
      - "../inventory/group_vars/all.yml"
      tags: always
    
    #- name: Ensure Python is installed (Linux)
    #  package:
    #    name: python3
    #    state: present
    #  when: ansible_os_family in ['RedHat', 'Debian']
    #  tags: 
    #    - prerequisites
    
    - name: Create temp directory (Windows)
      win_file:
        path: C:\Temp
        state: directory
      when: ansible_os_family == 'Windows'
      tags:
        - prerequisites
  
  roles:
    - role: common
      tags: [common, install]
    
    - role: linux_install
      when: ansible_os_family in ['RedHat', 'Debian']
      tags: [install, linux]
    
    - role: windows_install
      when: ansible_os_family == 'Windows'
      tags: [install, windows]
    
    - role: validation
      tags: [validate]