# Sandbox environment specific variables - unchanged
monitor_vm_infra_metrics:
- cpu
- memory: null
- disk:
  - /
  - /var
  - /var/log
- process:
  - name:
    - ansible:
      - enable_logging: true
      - add_labels:
        - my_custom_label: my_custom_label_value
    - remove_labels:
      - k8s.namespace_name
      - k8s.pod_name
      - k8s.container_name
    - docker
    - sshd

debug: true

sent_to:
- grafana_cloud:
  - monitor_vm_infra_metrics
- splunk_enterprise:
- prometheus:
  - send_metrics_with_labels:
    - k8s.namespace.name: monitoring
