---
# Check if OpenTelemetry Collector is installed on Linux
- name: Find otelcol-contrib binary in PATH
  ansible.builtin.command: "command -v otelcol-contrib"
  register: otelcol_binary
  ignore_errors: yes  
  changed_when: false  

- name: Set installation status fact
  ansible.builtin.set_fact:
    otelcol_installed: "{{ otelcol_binary.stdout }}"