---
# Tasks for uninstalling OpenTelemetry Collector
- name: Check installation status
  include_tasks: "{{ (ansible_os_family | lower ~ '_check.yml') if ansible_os_family == 'Windows' else 'linux_check.yml' }}"
  when: ansible_os_family in ['RedHat', 'Debian', 'Windows']

- name: Uninstall OpenTelemetry Collector
  include_tasks: "{{ (ansible_os_family | lower ~ '_uninstall.yml') if ansible_os_family == 'Windows' else 'linux_uninstall.yml' }}"
  when: 
    - ansible_os_family in ['RedHat', 'Debian', 'Windows']
    - otelcol_installed | default(false)

- name: Display uninstallation status
  debug:
    msg: "OpenTelemetry Collector has been uninstalled from {{ inventory_hostname }}"
  when: otelcol_installed | default(false)

- name: Display not installed message
  debug:
    msg: "OpenTelemetry Collector was not installed on {{ inventory_hostname }}"
  when: not otelcol_installed | default(false)